name: prestashop_api
description: A Dart package designed to simplify interaction with PrestaShop websites by providing
  streamlined API integration, automatic model generation, data serialization, and exception
  handling.
version: 1.4.0
homepage: https://github.com/MouradJEMAIL/prestashop_api
repository: https://github.com/MouradJEMAIL/prestashop_api
issue_tracker: https://github.com/MouradJEMAIL/prestashop_api/issues
topics:
  - api
  - prestashop
  - ecommerce
  - rest
  - webservice

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  injectable: ^2.7.1+4
  json_annotation: ^4.9.0
  logger: ^2.6.2

dev_dependencies:
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.3
  lint: ^2.8.0
  mockito: ^5.6.1
  test: ^1.28.0

dependency_overrides:
  analyzer: ^8.1.1
  dart_style: 3.1.2
